### ISSUE TITLE
docker-compose should persist data by default

### ISSUE THREAD

**Issue by ColdHeat** [isislab/CTFd#185]
This should be all that's needed but should go through the usual "testing if it works" flow

```yaml
ctfd:
  build: .
  restart: always 
  ports:
    - "8000:8000" 
  environment: 
    - DATABASE_URL=mysql+pymysql://root@db/ctfd
  volumes_from:
    - data:rw
  links:
    - db:db

db:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  volumes_from:
    - data:rw
  
data:
  image: mysql
  restart: always
  volumes:
    - .data/mysql:/var/lib/mysql
    - .data/CTFd:/opt/CTFd/CTFd/logs
  command: "tail -f /dev/null"
```
